name: DAST Scan

on:
  workflow_dispatch:

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t diwa .

      - name: Run app container
        run: |
          docker run -d --name diwa -p 8080:80 diwa
          sleep 5

      - name: Verify app is running
        run: curl --fail http://localhost:8080

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm -v ${{ github.workspace }}:/zap/wrk ghcr.io/zaproxy/zap-baseline:latest -t http://host.docker.internal:8080

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-baseline-report
          path: report.html

      - name: Stop app container
        run: docker stop diwa
