name: DAST Scan

on:
  workflow_dispatch:

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t diwa .

      - name: Run app container
        run: |
          docker run -d --name diwa -p 8080:80 diwa
          sleep 5

      - name: Verify app is running
        run: curl --fail http://localhost:8080

      - name: Run OWASP ZAP Baseline Scan (no artifact)
        run: |
          docker run --rm -v $(pwd):/zap/wrk ghcr.io/zaproxy/zap-baseline:latest \
          -t http://localhost:8080 -J zap_report.json -r zap_report.html

      - name: Stop container
        run: docker stop diwa
