name: DAST Scan

on:
  workflow_dispatch:

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --dns 8.8.8.8
        ports:
          - 8080:8080

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build app image
        run: docker build -t diwa .

      - name: Run app container
        run: |
          docker run -d --name diwa -p 8080:8080 diwa
          sleep 10  # daj czas na start

      - name: Check app
        run: curl --fail http://localhost:8080

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-a'
