name: DAST Scan with Nikto

on:
  workflow_dispatch:

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t diwa .

      - name: Run app container
        run: |
          docker run -d --name diwa -p 8080:80 diwa
          sleep 5

      - name: Verify app is running
        run: curl --fail http://localhost:8080

      - name: Run Nikto Scan and save report
        run: |
          docker run --rm --network="host" nikto/nikto -h http://localhost:8080 -o nikto_report.txt -Format txt
          cat nikto_report.txt

      - name: Create issue with Nikto report
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Nikto DAST Scan Report
          content-filepath: nikto_report.txt
          labels: security, nikto

      - name: Stop app container
        run: docker stop diwa
