name: DAST Scan

on:
  workflow_dispatch:

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t diwa .

      - name: Run app container
        run: |
          docker run -d --name diwa -p 8080:80 diwa
          sleep 5

      - name: Verify app is running
        run: curl --fail http://localhost:8080

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-a'
          allow_issue_writing: true
          issue_title: 'ZAP Scan Baseline Report'
          fail_action: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop container
        run: docker stop diwa
