name: Secret Scan with Gitleaks

on:
  workflow_dispatch:

jobs:
  gitleaks-scan:
    name: Scan for Secrets with Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Run Gitleaks Scan
        run: |
          gitleaks detect --source . \
                          --report-path gitleaks-report.json \
                          --report-format json || true

      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
