name: Secret Scan with truffleHog

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run truffleHog scan
        uses: trufflesecurity/trufflehog@v3
        with:
          scan_type: 'filesystem'
          path: '.'
