name: Secret Scan with truffleHog CLI

on:
  workflow_dispatch:

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install truffleHog
        run: pip install truffleHog

      - name: Run truffleHog scan and save output
        run: trufflehog --repo-path . --json > trufflehog-results.json || true

      - name: Upload truffleHog results artifact
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-results
          path: trufflehog-results.json
