name: Secret Scan with truffleHog CLI

on:
  workflow_dispatch:

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python and pip
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install truffleHog
        run: pip install truffleHog

      - name: Run truffleHog scan
        run: trufflehog filesystem . --exit-zero
