name: Secret Scan with truffleHog CLI

on:
  workflow_dispatch:

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install truffleHog v3 (trufflehog3)
        run: pip install trufflehog3

      - name: Run truffleHog3 scan and save output
        run: trufflehog3 --repo-path . --json > trufflehog-results.json || true

      - name: Upload truffleHog3 results artifact
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: trufflehog-results.json
